
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chris
 */

public class AFinanceManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AResidentManagement.class.getName());

    /**
     * Creates new form AdminDash
     */
    public AFinanceManagement() {
        initComponents();
        WardViewTable.setDefaultEditor(Object.class, null);
        table_update();
        
        WardViewTable.getSelectionModel().addListSelectionListener(e -> {
            // selection listener placeholder (no-op)
        });

        // Populate combo box with wards (exclude admin 'Z') and load admin savings
        populateWardCombo();
        loadAdminSavings();
                }
    
    Connection con1;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        RepButton = new javax.swing.JButton();
        EButton = new javax.swing.JButton();
        FButton = new javax.swing.JButton();
        RButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addAmountTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        AddAmount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        WardViewTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        savingsLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        WardComboBox = new javax.swing.JComboBox<>();
        allotAmountTextField = new javax.swing.JTextField();
        AllotButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Admin Dashboard");

        logoutButton.setBackground(new java.awt.Color(204, 204, 255));
        logoutButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(102, 102, 102));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        RepButton.setBackground(new java.awt.Color(204, 204, 255));
        RepButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        RepButton.setForeground(new java.awt.Color(255, 255, 255));
        RepButton.setText("Report");
        RepButton.setAlignmentY(0.2F);
        RepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepButtonActionPerformed(evt);
            }
        });

        EButton.setBackground(new java.awt.Color(204, 204, 255));
        EButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        EButton.setForeground(new java.awt.Color(255, 255, 255));
        EButton.setText("Employees");
        EButton.setAlignmentY(0.2F);
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });

        FButton.setBackground(new java.awt.Color(204, 204, 255));
        FButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        FButton.setForeground(new java.awt.Color(255, 255, 255));
        FButton.setText("Finance");
        FButton.setAlignmentY(0.2F);
        FButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FButtonActionPerformed(evt);
            }
        });

        RButton.setBackground(new java.awt.Color(204, 204, 255));
        RButton.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        RButton.setForeground(new java.awt.Color(255, 255, 255));
        RButton.setText("Residents");
        RButton.setAlignmentY(0.2F);
        RButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RButton, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addComponent(FButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addComponent(EButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addComponent(RepButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(RButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(FButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(EButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(RepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(125, Short.MAX_VALUE)))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Finance");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Savings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setText("Add Amount :");

        AddAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddAmount.setText("Add");
        AddAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(addAmountTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(addAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddAmount)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        WardViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ward", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(WardViewTable);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 51));
        jLabel11.setText("Current Balance : ");

        savingsLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        savingsLabel.setForeground(new java.awt.Color(0, 204, 51));
        savingsLabel.setText("$$$$");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 51));
        jLabel13.setText("Rs.");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Allot Amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Ward : ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setText("Amount :");

        AllotButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AllotButton.setText("Add Funds");
        AllotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AllotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(allotAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(WardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(allotAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AllotButton)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(savingsLabel)
                    .addComponent(jLabel13))
                .addGap(8, 8, 8)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(113, 113, 113))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void table_update(){
        try {
            int c;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/eden","root","");
            pst = con1.prepareStatement("select ward_id, name, assigned_amount from wards WHERE ward_id <> ?");
            pst.setString(1, "Z");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            
            DefaultTableModel d = (DefaultTableModel)WardViewTable.getModel();
            d.setRowCount(0);
       
            while(rs.next()){
                Vector<String> v2 = new Vector<>();
                v2.add(rs.getString("ward_id"));
                v2.add(rs.getString("name"));
                v2.add(rs.getString("assigned_amount"));
                d.addRow(v2);
            }
        } catch (ClassNotFoundException ex) {
            System.getLogger(AResidentManagement.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.getLogger(AResidentManagement.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    // Populate WardComboBox with wards except admin (ward_id = 'Z')
    private void populateWardCombo() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/eden","root",
                    "");
            pst = con1.prepareStatement("SELECT ward_id, name FROM wards WHERE ward_id <> ?");
            pst.setString(1, "Z");
            ResultSet rs = pst.executeQuery();
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            while (rs.next()) {
                String id = rs.getString("ward_id");
                String name = rs.getString("name");
                model.addElement(id + " - " + name);
            }
            WardComboBox.setModel(model);
            rs.close();
            pst.close();
            con1.close();
        } catch (ClassNotFoundException | SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Load admin assigned_amount into savingsLabel
    private void loadAdminSavings() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/eden","root",
                    "");
            pst = con1.prepareStatement("SELECT assigned_amount FROM wards WHERE ward_id = ?");
            pst.setString(1, "Z");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                double amt = rs.getDouble("assigned_amount");
                if (rs.wasNull()) amt = 0.0;
                savingsLabel.setText(String.format("%.2f", amt));
            }
            rs.close();
            pst.close();
            con1.close();
        } catch (ClassNotFoundException | SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    
    private void AllotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllotButtonActionPerformed
        // Validate selection and amount
        if (WardComboBox.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this, "No wards available to allot.", "No wards", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String selected = (String) WardComboBox.getSelectedItem();
        if (selected == null || !selected.contains(" - ")) {
            JOptionPane.showMessageDialog(this, "Please select a valid ward.", "Invalid selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String wardId = selected.split(" - ", 2)[0];
        String text = allotAmountTextField.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an amount to allot.", "Input required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double toAllot;
        try {
            toAllot = Double.parseDouble(text);
            if (toAllot <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a positive amount.", "Invalid input", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric amount.", "Invalid input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Perform transfer: subtract from admin (Z) and add to selected ward
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/eden","root","");
            con1.setAutoCommit(false);

            // Read admin amount
            try (PreparedStatement pstAdmin = con1.prepareStatement("SELECT assigned_amount FROM wards WHERE ward_id = ? FOR UPDATE")) {
                pstAdmin.setString(1, "Z");
                ResultSet rsAdmin = pstAdmin.executeQuery();
                if (!rsAdmin.next()) {
                    rsAdmin.close();
                    con1.rollback();
                    con1.setAutoCommit(true);
                    con1.close();
                    JOptionPane.showMessageDialog(this, "Admin ward not found.", "Not found", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                double adminAmt = rsAdmin.getDouble("assigned_amount");
                if (rsAdmin.wasNull()) adminAmt = 0.0;
                rsAdmin.close();

                if (adminAmt < toAllot) {
                    con1.rollback();
                    con1.setAutoCommit(true);
                    con1.close();
                    JOptionPane.showMessageDialog(this, "Insufficient admin funds to allot the requested amount.", "Insufficient funds", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                double newAdmin = adminAmt - toAllot;

                // Update admin
                try (PreparedStatement pstUpdAdmin = con1.prepareStatement("UPDATE wards SET assigned_amount = ? WHERE ward_id = ?")) {
                    pstUpdAdmin.setDouble(1, newAdmin);
                    pstUpdAdmin.setString(2, "Z");
                    pstUpdAdmin.executeUpdate();
                }

                // Read and update target ward
                try (PreparedStatement pstTarget = con1.prepareStatement("SELECT assigned_amount FROM wards WHERE ward_id = ? FOR UPDATE")) {
                    pstTarget.setString(1, wardId);
                    ResultSet rsTarget = pstTarget.executeQuery();
                    if (!rsTarget.next()) {
                        rsTarget.close();
                        con1.rollback();
                        con1.setAutoCommit(true);
                        con1.close();
                        JOptionPane.showMessageDialog(this, "Target ward not found.", "Not found", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    double targetAmt = rsTarget.getDouble("assigned_amount");
                    if (rsTarget.wasNull()) targetAmt = 0.0;
                    rsTarget.close();

                    double newTarget = targetAmt + toAllot;
                    try (PreparedStatement pstUpdTarget = con1.prepareStatement("UPDATE wards SET assigned_amount = ? WHERE ward_id = ?")) {
                        pstUpdTarget.setDouble(1, newTarget);
                        pstUpdTarget.setString(2, wardId);
                        pstUpdTarget.executeUpdate();
                    }
                }

                con1.commit();
                con1.setAutoCommit(true);
                con1.close();

                // Update UI
                loadAdminSavings();
                table_update();
                allotAmountTextField.setText("");
                JOptionPane.showMessageDialog(this, "Amount allotted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "DB Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AllotButtonActionPerformed

    

    private void RButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonActionPerformed
        this.dispose();
        new AResidentManagement().setVisible(true);
    }//GEN-LAST:event_RButtonActionPerformed

    private void FButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FButtonActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        this.dispose();
        new AEmployeeManagement().setVisible(true);
    }//GEN-LAST:event_EButtonActionPerformed

    private void RepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepButtonActionPerformed
        this.dispose();
        new AReport().setVisible(true);
    }//GEN-LAST:event_RepButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // Show confirmation dialog before logout
        int confirmResult = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmResult == JOptionPane.YES_OPTION) {
            // Close current frame
            this.dispose();

            // Open login frame
            java.awt.EventQueue.invokeLater(() -> {
                new Login().setVisible(true);
            });
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void AddAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAmountActionPerformed
        // Read and validate input
        String text = addAmountTextField.getText().trim();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an amount to add.", "Input required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double toAdd;
        try {
            toAdd = Double.parseDouble(text);
            if (toAdd <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a positive amount.", "Invalid input", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric amount.", "Invalid input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update the assigned_amount for ward_id='Z' and name='Admin'
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/eden","root","");

            // Get current assigned amount
            pst = con1.prepareStatement("SELECT assigned_amount FROM wards WHERE ward_id = ? AND name = ?");
            pst.setString(1, "Z");
            pst.setString(2, "Admin Ward");
            ResultSet rs = pst.executeQuery();
            double current = 0.0;
            if (rs.next()) {
                current = rs.getDouble("assigned_amount");
                if (rs.wasNull()) current = 0.0;
            } else {
                rs.close();
                pst.close();
                con1.close();
                JOptionPane.showMessageDialog(this, "Admin ward (Z) not found in wards table.", "Not found", JOptionPane.ERROR_MESSAGE);
                return;
            }
            rs.close();
            pst.close();

            double updated = current + toAdd;

            // Persist the updated value
            pst = con1.prepareStatement("UPDATE wards SET assigned_amount = ? WHERE ward_id = ? AND name = ?");
            pst.setDouble(1, updated);
            pst.setString(2, "Z");
            pst.setString(3, "Admin Ward");
            int rows = pst.executeUpdate();
            pst.close();
            con1.close();

            if (rows > 0) {
                // Reflect change in UI
                savingsLabel.setText(String.format("%.2f", updated));
                table_update();
                addAmountTextField.setText("");
                JOptionPane.showMessageDialog(this, "Amount added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update assigned amount.", "Update failed", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "DB Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AResidentManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAmount;
    private javax.swing.JButton AllotButton;
    private javax.swing.JButton EButton;
    private javax.swing.JButton FButton;
    private javax.swing.JButton RButton;
    private javax.swing.JButton RepButton;
    private javax.swing.JComboBox<String> WardComboBox;
    private javax.swing.JTable WardViewTable;
    private javax.swing.JTextField addAmountTextField;
    private javax.swing.JTextField allotAmountTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel savingsLabel;
    // End of variables declaration//GEN-END:variables
}
